# Generated by Django 4.1.7 on 2023-06-07 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('legajo', models.CharField(max_length=100, verbose_name='Legajo')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del grupo:')),
                ('tipo', models.CharField(choices=[('Público', 'Público'), ('Privado', 'Privado')], max_length=10)),
                ('tema', models.CharField(max_length=200, verbose_name='Tema del grupo')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción del grupo')),
                ('proximo_encuentro', models.DateField(verbose_name='Próxima reunión')),
                ('estudiante', models.ManyToManyField(to='gbweb.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('lider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('legajo', models.CharField(max_length=100, verbose_name='Legajo')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('terminado', models.BooleanField(default=False)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbweb.grupo')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbweb.lider'),
        ),
    ]
