# Generated by Django 4.1.7 on 2023-05-30 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='grupo',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='titulo',
            new_name='title',
        ),
    ]
