# Generated by Django 4.2.1 on 2023-06-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbweb', '0002_rename_descripcion_tarea_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='password',
            field=models.CharField(max_length=50, null=True, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='persona',
            name='username',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre de usuario'),
        ),
    ]
