# Generated by Django 4.1.7 on 2023-06-06 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gbweb', '0003_persona_password_persona_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gbweb.persona')),
                ('legajo', models.CharField(max_length=100, verbose_name='Legajo')),
                ('cursos', models.ManyToManyField(to='gbweb.grupo')),
            ],
        ),
    ]
